const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const postsDir = path.join(rootDir, "posts");
const outputDir = path.join(rootDir, "blog");
const postsIndexFile = path.join(postsDir, "posts.json");
const blogIndexFile = path.join(rootDir, "blog-posts.html");
const legacyPostFile = path.join(rootDir, "blog.html");

const generatedMarker = "<!-- Generated by generate-index.js. Do not edit by hand. -->";

const site = {
  title: "micah li",
  blogTitle: "blog",
  blogSubtitle: "a place for many non-math related things. looking for math? look at my homepage",
  diaryPath: "math-diary.html",
  photosPath: "photos.html",
};

function ensureDirectory(directory) {
  if (!fs.existsSync(directory)) {
    fs.mkdirSync(directory, { recursive: true });
  }
}

function cleanGeneratedPosts() {
  if (!fs.existsSync(outputDir)) return;

  for (const file of fs.readdirSync(outputDir)) {
    const filePath = path.join(outputDir, file);
    if (path.extname(filePath) !== ".html") continue;

    const content = fs.readFileSync(filePath, "utf8");
    if (content.includes(generatedMarker)) {
      fs.unlinkSync(filePath);
    }
  }
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value) {
  return escapeHtml(String(value).trim());
}

function stripQuotes(value) {
  const trimmed = String(value).trim();
  const first = trimmed[0];
  const last = trimmed[trimmed.length - 1];

  if ((first === '"' && last === '"') || (first === "'" && last === "'")) {
    return trimmed.slice(1, -1);
  }

  return trimmed;
}

function parseFrontmatterValue(value) {
  const trimmed = value.trim();

  if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
    const inner = trimmed.slice(1, -1).trim();
    if (!inner) return [];
    return inner.split(",").map((item) => stripQuotes(item));
  }

  return stripQuotes(trimmed);
}

function parseFrontmatterBlock(rawFrontmatter) {
  const data = {};

  for (const line of rawFrontmatter.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const match = trimmed.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;

    data[match[1]] = parseFrontmatterValue(match[2]);
  }

  return data;
}

function splitFrontmatter(source) {
  const normalized = source.replace(/\r\n/g, "\n");
  const lines = normalized.split("\n");

  if (lines[0]?.trim() !== "---") {
    return { frontmatter: {}, markdown: normalized.trim() };
  }

  const closeIndex = lines.findIndex((line, index) => index > 0 && line.trim() === "---");

  if (closeIndex === -1) {
    return { frontmatter: {}, markdown: normalized.trim() };
  }

  return {
    frontmatter: parseFrontmatterBlock(lines.slice(1, closeIndex).join("\n")),
    markdown: lines.slice(closeIndex + 1).join("\n").trim(),
  };
}

function titleFromSlug(slug) {
  return slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function stripMarkdown(markdown) {
  return markdown
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/!\[[^\]]*]\([^)]+\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]+\)/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/^>\s?/gm, "")
    .replace(/[*_~`#>|-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function truncateText(text, maxLength) {
  if (text.length <= maxLength) return text;

  const truncated = text.slice(0, maxLength).trim();
  const lastSpace = truncated.lastIndexOf(" ");

  return `${truncated.slice(0, lastSpace > 80 ? lastSpace : maxLength).trim()}...`;
}

function createExcerpt(markdown) {
  return truncateText(stripMarkdown(markdown), 155);
}

function dateSortValue(date) {
  const timestamp = Date.parse(`${date}T00:00:00Z`);
  return Number.isNaN(timestamp) ? 0 : timestamp;
}

function formatDate(date) {
  if (!date) return "";

  const parsed = new Date(`${date}T00:00:00Z`);
  if (Number.isNaN(parsed.getTime())) return date;

  return parsed.toLocaleDateString("en-US", {
    day: "numeric",
    month: "long",
    timeZone: "UTC",
    year: "numeric",
  });
}

function createPlaceholderStore() {
  const values = [];

  return {
    add(value) {
      const token = `\u0000${values.length}\u0000`;
      values.push(value);
      return token;
    },
    restore(value) {
      return value.replace(/\u0000(\d+)\u0000/g, (_, index) => values[Number(index)]);
    },
  };
}

function safeUrl(url, prefix = "") {
  const trimmed = String(url).trim().replace(/^<(.+)>$/, "$1");
  const isUnsafe = /^\s*javascript:/i.test(trimmed);
  const isExternal = /^(https?:|mailto:|tel:|data:)/i.test(trimmed);
  const isAnchored = trimmed.startsWith("#") || trimmed.startsWith("/");

  if (isUnsafe) return "#";
  if (!prefix || isExternal || isAnchored) return trimmed;

  return `${prefix}${trimmed}`;
}

function renderInline(markdown, prefix = "") {
  const placeholders = createPlaceholderStore();

  let rendered = String(markdown).replace(/`([^`]+)`/g, (_, code) => {
    return placeholders.add(`<code>${escapeHtml(code)}</code>`);
  });

  rendered = rendered.replace(/!\[([^\]]*)]\(([^)]+)\)/g, (_, alt, src) => {
    return placeholders.add(`<img src="${escapeAttribute(safeUrl(src, prefix))}" alt="${escapeAttribute(alt)}">`);
  });

  rendered = rendered.replace(/\[([^\]]+)]\(([^)]+)\)/g, (_, label, href) => {
    return placeholders.add(`<a href="${escapeAttribute(safeUrl(href, prefix))}">${escapeHtml(label)}</a>`);
  });

  rendered = escapeHtml(rendered)
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
    .replace(/__([^_]+)__/g, "<strong>$1</strong>")
    .replace(/\*([^*]+)\*/g, "<em>$1</em>")
    .replace(/_([^_]+)_/g, "<em>$1</em>");

  return placeholders.restore(rendered);
}

function isTableDivider(line) {
  return /^\s*\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?\s*$/.test(line);
}

function splitTableRow(line) {
  return line
    .trim()
    .replace(/^\|/, "")
    .replace(/\|$/, "")
    .split("|")
    .map((cell) => cell.trim());
}

function indentationWidth(value) {
  let width = 0;

  for (const character of value) {
    width += character === "\t" ? 4 - (width % 4) : 1;
  }

  return width;
}

function getListItem(line) {
  const match = line.match(/^([ \t]*)([-*+]|\d+\.)(?:[ \t]+(.*)|[ \t]*)$/);

  if (!match) return null;

  return {
    indent: indentationWidth(match[1]),
    text: (match[3] || "").trim(),
    type: /^\d+\.$/.test(match[2]) ? "ol" : "ul",
  };
}

function isBlockStart(lines, index) {
  const line = lines[index] || "";
  const nextLine = lines[index + 1] || "";

  return (
    /^```/.test(line) ||
    /^#{1,6}\s+/.test(line) ||
    /^>\s?/.test(line) ||
    getListItem(line) ||
    /^ {0,3}([-*_])(?:\s*\1){2,}\s*$/.test(line) ||
    (line.includes("|") && isTableDivider(nextLine))
  );
}

function renderListAtIndent(lines, index, indent, type, prefix) {
  const items = [];

  while (index < lines.length) {
    const item = getListItem(lines[index]);
    if (!item || item.indent < indent || (item.indent === indent && item.type !== type)) break;

    if (item.indent > indent) {
      if (!items.length) break;

      const nestedList = renderListAtIndent(lines, index, item.indent, item.type, prefix);
      items[items.length - 1].children.push(nestedList.html);
      index = nestedList.nextIndex;
      continue;
    }

    const itemContent = item.text ? [renderInline(item.text, prefix)] : [];
    const children = [];
    index += 1;

    while (index < lines.length) {
      if (!lines[index].trim()) break;

      const nextItem = getListItem(lines[index]);
      if (nextItem) {
        if (nextItem.indent > item.indent) {
          const nestedList = renderListAtIndent(lines, index, nextItem.indent, nextItem.type, prefix);
          children.push(nestedList.html);
          index = nestedList.nextIndex;
          continue;
        }

        break;
      }

      if (isBlockStart(lines, index)) break;

      const continuationIndent = indentationWidth(lines[index].match(/^[ \t]*/)[0]);
      if (continuationIndent < item.indent) break;

      itemContent.push(renderInline(lines[index].trim(), prefix));
      index += 1;
    }

    items.push({ children, content: itemContent.join(" ") });
  }

  const html = `<${type}>\n${items
    .map((item) => {
      const children = item.children.length ? `\n${item.children.join("\n")}` : "";
      return `  <li>${item.content}${children}</li>`;
    })
    .join("\n")}\n</${type}>`;

  return { html, nextIndex: index };
}

function renderList(lines, index, prefix) {
  const item = getListItem(lines[index]);
  if (!item) return null;

  return renderListAtIndent(lines, index, item.indent, item.type, prefix);
}

function renderTable(lines, prefix) {
  const header = splitTableRow(lines[0]);
  const bodyRows = lines.slice(2).map(splitTableRow);

  return [
    "<table>",
    "  <thead>",
    `    <tr>${header.map((cell) => `<th>${renderInline(cell, prefix)}</th>`).join("")}</tr>`,
    "  </thead>",
    "  <tbody>",
    ...bodyRows.map((row) => `    <tr>${row.map((cell) => `<td>${renderInline(cell, prefix)}</td>`).join("")}</tr>`),
    "  </tbody>",
    "</table>",
  ].join("\n");
}

function createHeadingId(text, usedIds) {
  const base = slugify(text.replace(/`([^`]+)`/g, "$1")) || "section";
  const count = usedIds.get(base) || 0;
  usedIds.set(base, count + 1);

  return count === 0 ? base : `${base}-${count + 1}`;
}

function markdownToHtml(markdown, usedHeadingIds = new Map(), prefix = "") {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const blocks = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index];

    if (!line.trim()) {
      index += 1;
      continue;
    }

    const fenceMatch = line.match(/^```([A-Za-z0-9_-]*)\s*$/);
    if (fenceMatch) {
      const language = fenceMatch[1];
      const codeLines = [];
      index += 1;

      while (index < lines.length && !/^```\s*$/.test(lines[index])) {
        codeLines.push(lines[index]);
        index += 1;
      }

      index += index < lines.length ? 1 : 0;
      const languageClass = language ? ` class="language-${escapeAttribute(language)}"` : "";
      blocks.push(`<pre><code${languageClass}>${escapeHtml(codeLines.join("\n"))}</code></pre>`);
      continue;
    }

    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (headingMatch) {
      const level = headingMatch[1].length;
      const text = headingMatch[2].trim();
      const id = createHeadingId(text, usedHeadingIds);
      blocks.push(`<h${level} id="${escapeAttribute(id)}">${renderInline(text, prefix)}</h${level}>`);
      index += 1;
      continue;
    }

    if (/^ {0,3}([-*_])(?:\s*\1){2,}\s*$/.test(line)) {
      blocks.push("<hr>");
      index += 1;
      continue;
    }

    if (line.includes("|") && isTableDivider(lines[index + 1] || "")) {
      const tableLines = [line, lines[index + 1]];
      index += 2;

      while (index < lines.length && lines[index].trim() && lines[index].includes("|")) {
        tableLines.push(lines[index]);
        index += 1;
      }

      blocks.push(renderTable(tableLines, prefix));
      continue;
    }

    if (/^>\s?/.test(line)) {
      const quoteLines = [];

      while (index < lines.length && (/^>\s?/.test(lines[index]) || !lines[index].trim())) {
        quoteLines.push(lines[index].replace(/^>\s?/, ""));
        index += 1;
      }

      blocks.push(`<blockquote>\n${markdownToHtml(quoteLines.join("\n"), usedHeadingIds, prefix)}\n</blockquote>`);
      continue;
    }

    const list = renderList(lines, index, prefix);
    if (list) {
      blocks.push(list.html);
      index = list.nextIndex;
      continue;
    }

    const paragraphLines = [];

    while (index < lines.length && lines[index].trim() && !isBlockStart(lines, index)) {
      paragraphLines.push(lines[index].trim());
      index += 1;
    }

    blocks.push(`<p>${renderInline(paragraphLines.join(" "), prefix)}</p>`);
  }

  return blocks.join("\n");
}

function readPost(file) {
  const filePath = path.join(postsDir, file);
  const slug = slugify(path.basename(file, ".md"));
  const source = fs.readFileSync(filePath, "utf8");
  const { frontmatter, markdown } = splitFrontmatter(source);
  const title = frontmatter.title || titleFromSlug(slug);
  const date = frontmatter.date || "";
  const tags = Array.isArray(frontmatter.tags) ? frontmatter.tags : [];
  const excerpt = frontmatter.excerpt || createExcerpt(markdown);

  return {
    date,
    excerpt,
    formattedDate: formatDate(date),
    html: markdownToHtml(markdown, new Map(), "../"),
    slug,
    source: `posts/${file}`,
    tags,
    title,
    url: `blog/${slug}.html`,
  };
}

function renderNav(prefix, activePage) {
  const aboutClass = activePage === "about" ? " active" : "";
  const photosClass = activePage === "photos" ? " active" : "";
  const blogClass = activePage === "blog" ? " active" : "";
  const diaryClass = activePage === "math-diary" ? " active" : "";

  return `
    <nav class="navbar">
        <div class="nav-container">
            <div class="nav-brand">
                <i class="fa fa-cube" aria-hidden="true"></i>
                <a href="${prefix}index.html" style="text-decoration: none"><span class="nav-title">${site.title}</span></a>
            </div>
            <div class="nav-menu" id="nav-menu">
                <a href="${prefix}index.html" class="nav-link${aboutClass}">about//</a>
                <a href="${prefix}${site.diaryPath}" class="nav-link${diaryClass}">math diary//</a>
                <a href="${prefix}${site.photosPath}" class="nav-link${photosClass}">photos//</a>
                <a href="${prefix}blog-posts.html" class="nav-link${blogClass}">blog//</a>
            </div>
            <div class="hamburger" id="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </nav>`;
}

function renderFooter() {
  return `
    <footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-brand">
                    <i class="fas fa-cube"></i>
                    <span>${site.title}</span>
                </div>
                <p>© ${new Date().getFullYear()}. made with <i class="fas fa-coffee"></i> and lots of commutative diagrams.</p>
            </div>
        </div>
    </footer>`;
}

function renderShell({ activePage = "blog", body, description = "", prefix = "", title }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    ${generatedMarker}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${escapeAttribute(description)}">
    <title>${escapeHtml(title)}</title>
    <link rel="stylesheet" href="${prefix}styles.css">
    <link rel="stylesheet" href="${prefix}blog-style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
${renderNav(prefix, activePage)}
${body}
${renderFooter()}
    <script src="${prefix}script.js"></script>
</body>
</html>
`;
}

function renderTags(tags, className) {
  if (!tags.length) return "";

  return `
                            <div class="${className}">
                                ${tags.map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("\n                                ")}
                            </div>`;
}

function renderPostCard(post) {
  return `
                        <article class="blog-post-card">
${renderTags(post.tags, "post-tags")}
                            <h2 class="post-title">
                                <a href="${escapeAttribute(post.url)}">${escapeHtml(post.title)}</a>
                            </h2>
                            ${post.date ? `
                            <div class="post-meta">
                                <i class="far fa-calendar"></i>
                                <time datetime="${escapeAttribute(post.date)}">${escapeHtml(post.formattedDate || post.date)}</time>
                            </div>` : ""}
                            ${post.excerpt ? `<p class="post-excerpt">${escapeHtml(post.excerpt)}</p>` : ""}
                        </article>`;
}

function renderBlogIndex(posts) {
  const postsHtml = posts.length
    ? posts.map(renderPostCard).join("\n")
    : '<p class="text-center">no posts found.</p>';

  const body = `
    <main class="container">
        <div class="blog-page">
            <div class="blog-header">
                <h1 class="hero-title">${site.blogTitle}</h1>
                <p class="hero-subtitle">${site.blogSubtitle}</p>
            </div>

            <section class="blog-post-list" aria-label="blog posts">
${postsHtml}
            </section>
        </div>
    </main>`;

  return renderShell({
    body,
    description: site.blogSubtitle,
    title: `${site.title} - ${site.blogTitle}`,
  });
}

function renderPostPage(post) {
  const body = `
    <main class="container">
        <div class="blog-page blog-article-page">
            <a href="../blog-posts.html" class="back-link">
                <i class="fas fa-arrow-left"></i> back to blog//
            </a>

            <article class="article-content">
                <header class="article-header">
${renderTags(post.tags, "article-tags")}
                    <h1 class="article-title">${escapeHtml(post.title)}</h1>
                    ${post.date ? `
                    <div class="article-meta">
                        <div class="meta-item">
                            <i class="far fa-calendar"></i>
                            <time datetime="${escapeAttribute(post.date)}">${escapeHtml(post.formattedDate || post.date)}</time>
                        </div>
                    </div>` : ""}
                </header>

                <div class="markdown-content">
${post.html}
                </div>

                <footer class="article-footer">
                    <a href="../blog-posts.html" class="back-link">
                        <i class="fas fa-arrow-left"></i> all posts//
                    </a>
                </footer>
            </article>
        </div>
    </main>`;

  return renderShell({
    body,
    description: post.excerpt,
    prefix: "../",
    title: `${post.title} - ${site.title}`,
  });
}

function renderLegacyRedirect() {
  const body = `
    <main class="container">
        <div class="blog-page">
            <article class="article-content">
                <h1 class="article-title">redirecting...</h1>
                <p class="post-excerpt">
                    This blog now uses static HTML pages. You should be sent to the right place automatically.
                    <a id="fallback-link" href="blog-posts.html">go to the blog index</a>
                </p>
            </article>
        </div>
    </main>
    <script>
        (function () {
            var params = new URLSearchParams(window.location.search);
            var post = params.get("post");
            var slug = post ? post.replace(/[^a-zA-Z0-9_-]/g, "") : "";
            var target = slug ? "blog/" + slug + ".html" : "blog-posts.html";
            var fallback = document.getElementById("fallback-link");
            fallback.href = target;
            fallback.textContent = slug ? "open this post" : "go to the blog index";
            window.location.replace(target);
        }());
    </script>`;

  return renderShell({
    body,
    description: "Compatibility redirect for older blog links.",
    title: `${site.title} - blog redirect`,
  });
}

function buildBlog() {
  console.log("Building blog from Markdown posts...");

  if (!fs.existsSync(postsDir)) {
    console.error(`Error: posts directory not found at ${postsDir}`);
    process.exit(1);
  }

  ensureDirectory(outputDir);
  cleanGeneratedPosts();

  const files = fs
    .readdirSync(postsDir)
    .filter((file) => path.extname(file) === ".md")
    .sort();

  const posts = files.map(readPost).sort((a, b) => dateSortValue(b.date) - dateSortValue(a.date));
  const slugs = new Set();

  for (const post of posts) {
    if (slugs.has(post.slug)) {
      console.error(`Error: duplicate post slug "${post.slug}"`);
      process.exit(1);
    }
    slugs.add(post.slug);
  }

  for (const post of posts) {
    const outputFile = path.join(outputDir, `${post.slug}.html`);
    fs.writeFileSync(outputFile, renderPostPage(post), "utf8");
  }

  const publicPosts = posts.map(({ html, ...post }) => post);

  fs.writeFileSync(postsIndexFile, JSON.stringify(publicPosts, null, 2), "utf8");
  fs.writeFileSync(blogIndexFile, renderBlogIndex(publicPosts), "utf8");
  fs.writeFileSync(legacyPostFile, renderLegacyRedirect(), "utf8");

  console.log(`Built ${posts.length} post page(s).`);
  console.log(`Updated ${path.relative(rootDir, blogIndexFile)} and ${path.relative(rootDir, postsIndexFile)}.`);
}

buildBlog();
