const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const photosDir = path.join(rootDir, "photos");
const outputFile = path.join(rootDir, "photos.html");
const generatedMarker = "<!-- Generated by generate-photos.js. Do not edit by hand. -->";
const imageExtensions = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif"]);

const site = {
  title: "micah li",
  blogPath: "blog-posts.html",
  diaryPath: "math-diary.html",
  photosPath: "photos.html",
};

const albumDetails = {
  arizona: {
    description: "desert roads, red rocks, canyon light",
    icon: "fa-mountain-sun",
  },
  berlin: {
    description: "city walks, museums, and cloudy streets",
    icon: "fa-city",
  },
  crochetkirby: {
    description: "soft yarn, round shapes, tiny triumphs",
    icon: "fa-heart",
    title: "crochet kirby",
  },
  "ben barnes concert": {
    description: "stage lights and concert snapshots",
    icon: "fa-music",
  },
  stanford: {
    description: "campus paths, arches, and quiet greens",
    icon: "fa-building-columns",
  },
};

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttribute(value) {
  return escapeHtml(String(value).trim());
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function naturalCompare(a, b) {
  return a.localeCompare(b, undefined, {
    numeric: true,
    sensitivity: "base",
  });
}

function titleFromFolder(folder) {
  if (albumDetails[folder]?.title) return albumDetails[folder].title;

  return folder
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/[-_]+/g, " ")
    .trim()
    .toLowerCase();
}

function encodePath(filePath) {
  return filePath
    .split("/")
    .map((part) => encodeURIComponent(part))
    .join("/");
}

function readAlbums() {
  if (!fs.existsSync(photosDir)) {
    console.error(`Error: photos directory not found at ${photosDir}`);
    process.exit(1);
  }

  return fs
    .readdirSync(photosDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const folder = entry.name;
      const folderPath = path.join(photosDir, folder);
      const files = fs
        .readdirSync(folderPath, { withFileTypes: true })
        .filter((file) => file.isFile() && imageExtensions.has(path.extname(file.name).toLowerCase()))
        .map((file) => file.name)
        .sort(naturalCompare);

      const slug = slugify(folder);
      const details = albumDetails[folder] || {};
      const title = titleFromFolder(folder);

      return {
        cover: files[0] ? encodePath(`photos/${folder}/${files[0]}`) : "",
        description: details.description || `${files.length} photo${files.length === 1 ? "" : "s"}`,
        files,
        folder,
        icon: details.icon || "fa-image",
        slug,
        title,
      };
    })
    .filter((album) => album.files.length > 0)
    .sort((a, b) => naturalCompare(a.title, b.title));
}

function renderNav(activePage) {
  const aboutClass = activePage === "about" ? " active" : "";
  const photosClass = activePage === "photos" ? " active" : "";
  const blogClass = activePage === "blog" ? " active" : "";
  const diaryClass = activePage === "math-diary" ? " active" : "";

  return `
    <nav class="navbar">
        <div class="nav-container">
            <div class="nav-brand">
                <i class="fa fa-cube" aria-hidden="true"></i>
                <a href="index.html" style="text-decoration: none"><span class="nav-title">${site.title}</span></a>
            </div>
            <div class="nav-menu" id="nav-menu">
                <a href="index.html" class="nav-link${aboutClass}">about//</a>
                <a href="${site.diaryPath}" class="nav-link${diaryClass}">math diary//</a>
                <a href="${site.photosPath}" class="nav-link${photosClass}">photos//</a>
                <a href="${site.blogPath}" class="nav-link${blogClass}">blog//</a>
            </div>
            <div class="hamburger" id="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </nav>`;
}

function renderFooter() {
  return `
    <footer class="footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-brand">
                    <i class="fas fa-cube"></i>
                    <span>${site.title}</span>
                </div>
                <p>© ${new Date().getFullYear()}. made with <i class="fas fa-coffee"></i> and lots of commutative diagrams.</p>
            </div>
        </div>
    </footer>`;
}

function numberFromText(value) {
  return Array.from(value).reduce((total, character) => total + character.charCodeAt(0), 0);
}

function pileStyle(album, index) {
  const seed = numberFromText(`${album.slug}-${index}`);
  const x = ((seed * 17) % 190) - 95;
  const y = ((seed * 31) % 126) - 63;
  const rotate = ((seed * 13) % 38) - 19;
  const scale = 0.88 + (((seed * 7) % 18) / 100);

  return [
    `--pile-x: ${x}px`,
    `--pile-y: ${y}px`,
    `--pile-rotate: ${rotate}deg`,
    `--pile-scale: ${scale.toFixed(2)}`,
    `--stack-depth: ${index}`,
  ].join("; ");
}

function renderAlbumCategory(album, isActive) {
  return `
                    <button class="album-category${isActive ? " active" : ""}" type="button" data-album-target="${escapeAttribute(album.slug)}" aria-pressed="${isActive ? "true" : "false"}">
                        <span class="album-category-title">${escapeHtml(album.folder)}</span>
                        <span class="album-category-count">${album.files.length}</span>
                    </button>`;
}

function renderPhotoPrint(album, file, index) {
  const src = encodePath(`photos/${album.folder}/${file}`);
  const label = `${album.title} photo ${index + 1}`;

  return `
                    <button class="loose-photo${index === 0 ? " is-top" : ""}" type="button" data-photo-position="${index}" style="${escapeAttribute(pileStyle(album, index))}" aria-label="${escapeAttribute(label)}">
                        <span class="photo-print">
                            <img src="${escapeAttribute(src)}" alt="${escapeAttribute(label)}" loading="${index === 0 ? "eager" : "lazy"}">
                        </span>
                    </button>`;
}

function renderAlbumPile(album, isActive) {
  return `
                <section class="album-pile${isActive ? " active" : ""}" data-album="${escapeAttribute(album.slug)}" aria-labelledby="${escapeAttribute(album.slug)}-title"${isActive ? "" : " hidden"}>
                    <div class="pile-header">
                        <div>
                            <h2 id="${escapeAttribute(album.slug)}-title">${escapeHtml(album.title)}</h2>
                            <p>${escapeHtml(album.description)}</p>
                        </div>
                        <p class="pile-count"><span data-current-photo>1</span> / ${album.files.length}</p>
                    </div>

                    <div class="photo-surface" data-photo-total="${album.files.length}">
${album.files.map((file, index) => renderPhotoPrint(album, file, index)).join("\n")}
                    </div>
                </section>`;
}

function renderPhotosPage(albums) {
  const totalPhotos = albums.reduce((total, album) => total + album.files.length, 0);

  return `<!DOCTYPE html>
<html lang="en">
<head>
    ${generatedMarker}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Photo archive for micah li.">
    <title>micah li - photos</title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
${renderNav("photos")}

    <main class="container">
        <section class="photos-page" aria-labelledby="photos-title">
            <header class="photos-header">
                <div>
                    <h1 id="photos-title" class="hero-title">photos</h1>
                    <p class="hero-subtitle">small collections from trips, shows, campus walks, and things made by hand</p>
                </div>
                <p class="photo-total">${totalPhotos} photos / ${albums.length} albums</p>
            </header>

            <div class="photo-desk">
                <aside class="album-sidebar" aria-label="photo albums">
${albums.map((album, index) => renderAlbumCategory(album, index === 0)).join("\n")}
                </aside>

                <div class="photo-dump" aria-live="polite">
${albums.map((album, index) => renderAlbumPile(album, index === 0)).join("\n")}
                </div>
            </div>
        </section>
    </main>
${renderFooter()}
    <script src="script.js"></script>
</body>
</html>
`;
}

function buildPhotos() {
  console.log("Building local photo gallery...");

  const albums = readAlbums();
  fs.writeFileSync(outputFile, renderPhotosPage(albums), "utf8");

  const totalPhotos = albums.reduce((total, album) => total + album.files.length, 0);
  console.log(`Built ${albums.length} album(s) with ${totalPhotos} photo(s).`);
  console.log(`Updated ${path.relative(rootDir, outputFile)}.`);
}

buildPhotos();
